version: "1"

services:
  laravel-cron:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://laravel-cron.zeabur.app

cron:
  - schedule: "* * * * *"
    command: "php /workspace/artisan schedule:run"
    service: laravel-cron